version: "3"

networks:
  guacamole-network:

services:
  init-guacamole-database:
    image: guacamole/guacamole:latest
    command:
      [ "/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
    volumes:
      - ./data/init:/init
    networks:
      - guacamole-network

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/init:/docker-entrypoint-initdb.d
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - init-guacamole-database
    networks:
      - guacamole-network

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped
    networks:
      - guacamole-network

  guacamole:
    image: guacamole/guacamole:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      # enable two factor authentication
      TOTP_ENABLED: ${TWO_FACTOR_AUTH}
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
      - guacd
    networks:
      - guacamole-network

  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    environment:
      SSL_CERT_KEY_NAME: ${SSL_CERT_KEY_NAME}
      SSL_CERT_FILE_NAME: ${SSL_CERT_FILE_NAME}
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates:rw,cached
      - ./config/certs:/etc/certs/
    depends_on:
      - guacamole
    networks:
      - guacamole-network
